a = int(input("specify the parameter a = "))
b = int(input("specify the parameter b = "))
print("a + b = ", a + b )
print("a - b = ", a - b )
print("a * b = ", a * b )
print("a / b = ", a / b )
print("a ** b = ", a ** b )
print("a // b  = ", a // b )
print("a % b  = ", a % b )
print("Have a good day!")